import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "VitalLink",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isUserLoggedIn = (await cookies()).has("accessToken");
  return (
    <main>
      <Navbar isUserLoggedIn={isUserLoggedIn} />
      {children}
      <Footer />
    </main>
  );
}
