import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import RecoilProvider from "@/components/RecoilProvider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VitalLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark w-dvh h-dvh">
      <body className={`${poppins.className} antialiased w-full h-full`}>
        <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
}
