import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <nav className="fixed top-0 left-0 w-full z-10 bg-white px-64 flex justify-between">
        <Image
          src={"/assets/logo.jpg"}
          width={400}
          height={400}
          alt="logo"
          className="object-cover h-16 w-32"
        />
        <div className="flex gap-32 items-center">
          <Link href={"/auth/signup"} className="text-black font-bold">
            Sign Up
          </Link>
          <Link href={"/auth/login"} className="text-black font-bold">
            Login
          </Link>
        </div>
      </nav>
      {children}
    </main>
  );
}
