import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "VitalLink",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar
        user={{
          id: "1",
          username: "Gamingstein",
          avatar: "",
          email: "something",
        }}
      />
      {children}
      <Footer />
    </main>
  );
}
